services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:3001"
    depends_on:
      - backend

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
       DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?schema=public
    command: sh -c "./wait-for-it.sh db:${DB_PORT} -- npx prisma migrate dev && npx tsx ./prisma/seed.ts && npm run start"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
